" sensible
syntax on
se is
se ic
se nu
se rnu
se cc=80
se nowrap
se sh=zsh
se equalprg=gt

" higlight
nn <silent> <c-c> :noh<cr>
se hls

" typo
ca W w
ca Q q
ca WQ wq
ca Wq w
ca E e

" pivot scroll
nn <silent> <c-j> <esc><c-e>j
nn <silent> <c-k> <esc><c-y>k

" indent
set sw=3 ts=3

" tab char
se list
se listchars=tab:\│\ ,trail:•,nbsp:+
