#!/bin/sh

alias l='ls'
alias tn='tmux'
alias ..='cd ..'
alias la='ls -a'
alias mv='mv -n'
alias rm='trash'
alias E="$EDITOR"
alias e="$EDITOR"
alias note="move"
alias ga='git add'
alias pup='pup -p'
alias gd='git diff'
alias glo='git log'
alias tac='tail -r'
alias ...='cd ../..'
alias gcl='git clone'
alias gss='git status'
alias tp='todaysplan'
alias ec='emacsclient'
alias gp='git push -u'
alias gc='git commit -v'
alias cpwd='pwd | pbcopy'
alias timestamp="date +%s"
alias watch='watch -cn0.1'
alias grep="grep --color=auto"
alias t='tmux attach &>/dev/null || tmux'
alias mp3='youtube-dl -x --audio-format mp3'
alias ll='ls -lh | awk "{ print \$NF }" | sed 1d'
alias find-executables='find . -perm +111 -type f'
alias captiveloop='until captive -i | grep -m 1 "Success"; do : ; done'
alias ip="ifconfig|grep -o 'inet \S*'|sed '/127\.0\.0/d'|grep -o '[0-9\.]\+'"

# Typo
alias gti='git'
alias les='less'
alias c..='cd ..'
alias tre='tree'; alias ter='tree'; alias rtee='tree'
alias :Q='exit'; alias :q='exit'; alias xeit=exit; alias q='exit';
alias :w="echo you such a vimmer"; alias :W="echo you such a vimmer";
alias :wq='exit'; alias :Wq='exit'; alias :wQ='exit'; alias :WQ='exit';
alias exi='exit'; alias eixt='exit'; alias exti='exit'; alias ixet='exit';
alias eitx='exit';

# Brew 
alias ps='brew search'
alias pu='brew update'
alias pi='brew install'
alias pr='brew uninstall'

# macOS Catalina
alias books='open /System/Applications/Books.app'
alias lpad='open /System/Applications/Launchpad.app'
alias calc='open /System/Applications/Calculator.app'
alias voice='open /System/Applications/VoiceMemos.app'
alias calendar='open /System/Applications/Calendar.app'
alias sleepmac="osascript -e 'tell application \"Finder\" to sleep '"
