#!/bin/sh

tmp() { #1:extension
	nvr --remote-wait "$(mktemp).$1";
}

notefromyoutube() { #1:title-one-hunk #2:youtube_link
	videoid=$(echo "$2" | grep -o 'v=[^\&]*' | cut -c3-)
	cd "${HOME}/Dropbox/document/blog/ihsanturk.dev/" || {
		echo >&2 "$(basename "$0"): No such directory."; return 1;
	}
	hugo new "posts/$1.md" && {
		printf "Notes from [this YouTube video](%s).\n\n[![video](http://img.youtube.com/vi/%s/0.jpg)](%s)" "$2" "$videoid" "$2">> "${HOME}/Dropbox/document/blog/ihsanturk.dev/content/posts/$1.md"
		nvr --remote-wait "${HOME}/Dropbox/document/blog/ihsanturk.dev/content/posts/$1.md"
	}
}

extract() {
	if [ -f "$1" ] ; then
		case "$1" in
			*.tar.bz2) tar xvjf "$1"  ;;
			*.tar.gz)  tar xvzf "$1"  ;;
			*.tar.xz)  tar xvJf "$1"  ;;
			*.bz2)     bunzip2 "$1"   ;;
			*.rar)     unrar x "$1"   ;;
			*.gz)      gunzip "$1"    ;;
			*.tar)     tar xvf "$1"   ;;
			*.tbz2)    tar xvjf "$1"  ;;
			*.tgz)     tar xvzf "$1"  ;;
			*.zip)     unzip "$1"     ;;
			*.Z)       uncompress "$1";;
			*.7z)      7z x "$1"      ;;
			*.xz)      unxz "$1"      ;;
			*.exe)     cabextract "$1";;
			*)         echo "\`$1': unrecognized file compression" ;;
		esac
	else
		echo "\`$1' is not a valid file"
	fi
}

# backward-kill-dir () {
#     local WORDCHARS=${WORDCHARS/\/}
#     zle backward-kill-word
# }

# zle -N backward-kill-dir
# bindkey '^[^?' backward-kill-dir
