"=== Plug ==="
call plug#begin('~/.local/share/nvim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
map <F3> :NERDTreeTabsToggle<CR>
let NERDTreeMapActivateNode='<space>'

Plug 'arcticicestudio/nord-vim', { 'branch': 'develop' }
let g:nord_italic = 1

call plug#end()

scriptencoding utf-8
syntax on
set hlsearch
set incsearch
set tabstop=2
set shiftwidth=2
set noswapfile
set ignorecase
set smartcase
set timeout
set timeoutlen=1000
set ttimeout
set ttimeoutlen=10
filetype plugin indent on
let g:netrw_dirhistmax = 0

"=== design ==="
set number
set cursorline
colorscheme nord
hi cursorline cterm=NONE ctermbg=black
hi CursorLineNr cterm=bold ctermfg=6 gui=bold guifg=yellow
hi LineNr ctermfg=238
hi StatusLine cterm=bold ctermfg=78 Ctermbg=0 gui=bold,reverse guibg=black

"=== global copy ==="
if has('unnamedplus')
	set clipboard=unnamed,unnamedplus
endif

"=== delete spaces ==="
augroup fmt
	autocmd!
	autocmd BufWritePost,FileWritePost * :silent! %s/\s\+$//
augroup END

"=== shortcut ==="
" TODO
" 	change tab to suggest variable
nmap <Tab> <Esc>:tabnext<CR>
nmap <S-Tab> <Esc>:tabprevious<CR>
nmap <F5> <Esc>:so ~/.config/nvim/vimrc<CR>
cnoreabbrev W w<CR>
cnoreabbrev Wq wq<CR>
cnoreabbrev qw wq<CR>
cnoreabbrev Q! q!<CR>
cnoreabbrev Q q<CR>
map q: :q
nnoremap <esc><esc> :noh<CR>

