"=== SETTING ==="
let mapleader = '\'
syntax on
set timeout
set hlsearch
set ttimeout
set incsearch
set smartcase
"set expandtab
set tabstop=4
set noswapfile
set ignorecase
set shiftwidth=4
set ttimeoutlen=10
set timeoutlen=1000
scriptencoding utf-8
filetype plugin indent on
let g:netrw_dirhistmax = 0
setglobal fileencoding=utf-8

"=== DESIGN ==="
set number
set cursorline
colorscheme delek
hi LineNr ctermfg=238
hi cursorline cterm=NONE ctermbg=237
hi CursorLineNr cterm=bold ctermfg=6
autocmd InsertEnter,InsertLeave * set cul!
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

highlight PmenuSel cterm=bold ctermfg=11 ctermbg=237
highlight PmenuBar ctermfg=65 ctermbg=220
highlight Pmenu ctermfg=7 ctermbg=239

hi StatusLine ctermbg=237
hi User1 ctermfg=65 ctermbg=237
hi User2 ctermfg=14 ctermbg=236 cterm=bold
hi User3 ctermfg=3 ctermbg=238
hi User4 ctermfg=6 ctermbg=238
hi User5 ctermfg=7 ctermbg=239
hi User6 ctermfg=12 ctermbg=241
hi User7 ctermfg=11 ctermbg=237

"=== STATUS LINE ==="
set laststatus=2
set statusline=
set statusline+=\ %1*[%n]                                "1 BufferNumber
set statusline+=\ %2*\ %f                                "2 FilePath
set statusline+=\ %3*\ %c\ %m%r%w%8*%=                   "3 ColumnNumber
set statusline+=\ %4*\ %y                                "4 FileType
set statusline+=\ %5*\ [%{&ff}]                          "5 FileFormat
set statusline+=\ %6*\ [%{''.(&fenc!=''?&fenc:&enc).''}] "6 Encoding
set statusline+=\ %7*\ %P\                               "7 Modified? Readonly? Top/bot.

"=== GLOBAL COPY ==="
if has('unnamedplus')
	set clipboard=unnamed,unnamedplus
endif

"=== PERSISTENT UNDO ==="
if has('persistent_undo')
  set undofile
  set undodir=~/.cache/vim
endif

"=== DELETE WITHOUT CUT ==="
nmap <leader>d "_d

"=== DELETE SPACES END OF LINES ==="
augroup fmt
	autocmd!
	autocmd BufWritePost,FileWritePost * :silent! %s/\s\+$//
augroup END

"=== SHORTCUT ==="
nmap n nzz
nmap N Nzz
nmap <Tab> :bn<CR>
nmap <S-Tab> :bp<CR>
nmap <esc><esc> :noh<CR>
nmap <leader>r :so ~/.config/nvim/vimrc<CR>
tno <Esc> <C-\><C-n>

map q: :q
cnorea W w
cnorea Q q
cnorea qw wq
cnorea Wq wq
cnorea Q! q!

"=== COMMENT ==="
"c,cpp
autocmd FileType c,cpp nmap <leader>c mxA */<esc>I/* <esc>`x3l:noh<CR>
autocmd FileType c,cpp nmap <leader>u :s/\/\* //g<CR>:s/ \*\///g<CR>:noh<CR>
autocmd FileType c,cpp vmap <leader>c <esc>`>a */<esc>`<i/*<esc>`>:noh<CR>
autocmd FileType c,cpp vmap <leader>u :s/\/\*//g<CR>gv:s/ \*\///g<CR>:noh<CR>
