#!/bin/sh
# Usage: img2txt [options] IMAGE_FILE
#
# Extract text from image file as text using tesseract.
#
# Arguments:
#   IMAGE_FILE  input image file
#
# Options:
#   -h --help
#   -l LANG --lang LANG
#
source docopts.sh --auto "$@"

tmpoutput=$(mktemp).txt
tesseract $image $tmpoutput -l $lang && cat $tmpoutput
