#!/bin/bash

. ${HOME}/colors/bash_colors.sh

printf "Time          : $(date +"%T")\n"
printf "Battery       : $(cat /sys/class/power_supply/BAT1/capacity)\n"
printf "Volume        : \n"
printf "Brightness    : $(($(cat /sys/class/backlight/intel_backlight/brightness)/75))\n\n"

printf "Wifi          : \n"
printf "Vpn           : \n"
printf "Ethernet      : \n\n"

printf "Disk /        : $(df -h 2>/dev/null | grep sda3 | tr "  " " " | awk '{printf $4}')B\n"
printf "Disk /home    : $(df -h 2>/dev/null | grep sda4 | tr "  " " " | awk '{printf $4}')B\n"
printf "Disk /media/d : $(df -h 2>/dev/null | grep sdb1 | tr "  " " " | awk '{printf $4}')B\n\n"
